name: 'Request to sign Contributor License Agreement (CLA Assistant Lite)'
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: 'CLA Assistant Lite'
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the ACLA Document and I hereby sign the ACLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'contributing/acla-v1.0-signed-contributors.json'
          path-to-document: 'https://github.com/pentest-a2p2v/pentest-a2p2v/blob/main/contributing/ACLA.md'
          branch: 'acla-signed-contributors'
          allowlist: ''
          remote-organization-name: pentest-a2p2v
          remote-repository-name: pentest-a2p2v
          signed-commit-message: '[bot] CLA Assistant Lite: ACLA signed by $contributorName'
          create-file-commit-message: '[bot] CLA Assistant Lite: Creating file for ACLA signed users'
          custom-pr-sign-comment: 'I have read the ACLA Document and I hereby sign the ACLA'

